name: automerge_workflow

on:
  pull_request:
    types: [opened, edited, reopened, labeled]
    paths:
    - 'Contributors.md'

jobs:
  automerge_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: merge-pr
        uses: ./.github/actions/automerge
        if: ${{github.event.pull_request.additions == 1 || (github.event.pull_request.additions == 2 && github.event.pull_request.deletions == 1)}}
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          number: ${{github.event.pull_request.number}}